/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaRouteImport } from './routes/wa'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapIndexDotxmlRouteImport } from './routes/sitemap-index[.]xml'
import { Route as SitemapImagesDotxmlRouteImport } from './routes/sitemap-images[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SectorsRouteImport } from './routes/sectors'
import { Route as SectorRouteImport } from './routes/sector'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PressRouteImport } from './routes/press'
import { Route as PlatformsRouteImport } from './routes/platforms'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessSetupRouteImport } from './routes/business-setup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForumPostIdRouteImport } from './routes/forum.$postId'
import { Route as DotwellKnownSecurityDottxtRouteImport } from './routes/[.]well-known.security[.]txt'

const WaRoute = WaRouteImport.update({
  id: '/wa',
  path: '/wa',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndexDotxmlRoute = SitemapIndexDotxmlRouteImport.update({
  id: '/sitemap-index.xml',
  path: '/sitemap-index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapImagesDotxmlRoute = SitemapImagesDotxmlRouteImport.update({
  id: '/sitemap-images.xml',
  path: '/sitemap-images.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsRoute = SectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorRoute = SectorRouteImport.update({
  id: '/sector',
  path: '/sector',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformsRoute = PlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSetupRoute = BusinessSetupRouteImport.update({
  id: '/business-setup',
  path: '/business-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumPostIdRoute = ForumPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => ForumRoute,
} as any)
const DotwellKnownSecurityDottxtRoute =
  DotwellKnownSecurityDottxtRouteImport.update({
    id: '/.well-known/security.txt',
    path: '/.well-known/security.txt',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/business-setup': typeof BusinessSetupRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/events': typeof EventsRoute
  '/forum': typeof ForumRouteWithChildren
  '/home': typeof HomeRoute
  '/leadership': typeof LeadershipRoute
  '/platform': typeof PlatformRoute
  '/platforms': typeof PlatformsRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sector': typeof SectorRoute
  '/sectors': typeof SectorsRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/sitemap-images.xml': typeof SitemapImagesDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wa': typeof WaRoute
  '/.well-known/security.txt': typeof DotwellKnownSecurityDottxtRoute
  '/forum/$postId': typeof ForumPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/business-setup': typeof BusinessSetupRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/events': typeof EventsRoute
  '/forum': typeof ForumRouteWithChildren
  '/home': typeof HomeRoute
  '/leadership': typeof LeadershipRoute
  '/platform': typeof PlatformRoute
  '/platforms': typeof PlatformsRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sector': typeof SectorRoute
  '/sectors': typeof SectorsRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/sitemap-images.xml': typeof SitemapImagesDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wa': typeof WaRoute
  '/.well-known/security.txt': typeof DotwellKnownSecurityDottxtRoute
  '/forum/$postId': typeof ForumPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/business-setup': typeof BusinessSetupRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/events': typeof EventsRoute
  '/forum': typeof ForumRouteWithChildren
  '/home': typeof HomeRoute
  '/leadership': typeof LeadershipRoute
  '/platform': typeof PlatformRoute
  '/platforms': typeof PlatformsRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sector': typeof SectorRoute
  '/sectors': typeof SectorsRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/sitemap-images.xml': typeof SitemapImagesDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wa': typeof WaRoute
  '/.well-known/security.txt': typeof DotwellKnownSecurityDottxtRoute
  '/forum/$postId': typeof ForumPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-us'
    | '/admin'
    | '/auth'
    | '/business-setup'
    | '/contact'
    | '/contact-us'
    | '/events'
    | '/forum'
    | '/home'
    | '/leadership'
    | '/platform'
    | '/platforms'
    | '/press'
    | '/privacy'
    | '/robots.txt'
    | '/sector'
    | '/sectors'
    | '/security'
    | '/services'
    | '/sitemap-images.xml'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/wa'
    | '/.well-known/security.txt'
    | '/forum/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-us'
    | '/admin'
    | '/auth'
    | '/business-setup'
    | '/contact'
    | '/contact-us'
    | '/events'
    | '/forum'
    | '/home'
    | '/leadership'
    | '/platform'
    | '/platforms'
    | '/press'
    | '/privacy'
    | '/robots.txt'
    | '/sector'
    | '/sectors'
    | '/security'
    | '/services'
    | '/sitemap-images.xml'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/wa'
    | '/.well-known/security.txt'
    | '/forum/$postId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-us'
    | '/admin'
    | '/auth'
    | '/business-setup'
    | '/contact'
    | '/contact-us'
    | '/events'
    | '/forum'
    | '/home'
    | '/leadership'
    | '/platform'
    | '/platforms'
    | '/press'
    | '/privacy'
    | '/robots.txt'
    | '/sector'
    | '/sectors'
    | '/security'
    | '/services'
    | '/sitemap-images.xml'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/wa'
    | '/.well-known/security.txt'
    | '/forum/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutUsRoute: typeof AboutUsRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BusinessSetupRoute: typeof BusinessSetupRoute
  ContactRoute: typeof ContactRoute
  ContactUsRoute: typeof ContactUsRoute
  EventsRoute: typeof EventsRoute
  ForumRoute: typeof ForumRouteWithChildren
  HomeRoute: typeof HomeRoute
  LeadershipRoute: typeof LeadershipRoute
  PlatformRoute: typeof PlatformRoute
  PlatformsRoute: typeof PlatformsRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SectorRoute: typeof SectorRoute
  SectorsRoute: typeof SectorsRoute
  SecurityRoute: typeof SecurityRoute
  ServicesRoute: typeof ServicesRoute
  SitemapImagesDotxmlRoute: typeof SitemapImagesDotxmlRoute
  SitemapIndexDotxmlRoute: typeof SitemapIndexDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WaRoute: typeof WaRoute
  DotwellKnownSecurityDottxtRoute: typeof DotwellKnownSecurityDottxtRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wa': {
      id: '/wa'
      path: '/wa'
      fullPath: '/wa'
      preLoaderRoute: typeof WaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-index.xml': {
      id: '/sitemap-index.xml'
      path: '/sitemap-index.xml'
      fullPath: '/sitemap-index.xml'
      preLoaderRoute: typeof SitemapIndexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-images.xml': {
      id: '/sitemap-images.xml'
      path: '/sitemap-images.xml'
      fullPath: '/sitemap-images.xml'
      preLoaderRoute: typeof SitemapImagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors': {
      id: '/sectors'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sector': {
      id: '/sector'
      path: '/sector'
      fullPath: '/sector'
      preLoaderRoute: typeof SectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platforms': {
      id: '/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof PlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-setup': {
      id: '/business-setup'
      path: '/business-setup'
      fullPath: '/business-setup'
      preLoaderRoute: typeof BusinessSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$postId': {
      id: '/forum/$postId'
      path: '/$postId'
      fullPath: '/forum/$postId'
      preLoaderRoute: typeof ForumPostIdRouteImport
      parentRoute: typeof ForumRoute
    }
    '/.well-known/security.txt': {
      id: '/.well-known/security.txt'
      path: '/.well-known/security.txt'
      fullPath: '/.well-known/security.txt'
      preLoaderRoute: typeof DotwellKnownSecurityDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ForumRouteChildren {
  ForumPostIdRoute: typeof ForumPostIdRoute
}

const ForumRouteChildren: ForumRouteChildren = {
  ForumPostIdRoute: ForumPostIdRoute,
}

const ForumRouteWithChildren = ForumRoute._addFileChildren(ForumRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutUsRoute: AboutUsRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BusinessSetupRoute: BusinessSetupRoute,
  ContactRoute: ContactRoute,
  ContactUsRoute: ContactUsRoute,
  EventsRoute: EventsRoute,
  ForumRoute: ForumRouteWithChildren,
  HomeRoute: HomeRoute,
  LeadershipRoute: LeadershipRoute,
  PlatformRoute: PlatformRoute,
  PlatformsRoute: PlatformsRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SectorRoute: SectorRoute,
  SectorsRoute: SectorsRoute,
  SecurityRoute: SecurityRoute,
  ServicesRoute: ServicesRoute,
  SitemapImagesDotxmlRoute: SitemapImagesDotxmlRoute,
  SitemapIndexDotxmlRoute: SitemapIndexDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WaRoute: WaRoute,
  DotwellKnownSecurityDottxtRoute: DotwellKnownSecurityDottxtRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
