/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaRouteImport } from './routes/wa'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SectorsRouteImport } from './routes/sectors'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlatformsRouteImport } from './routes/platforms'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessSetupRouteImport } from './routes/business-setup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForumPostIdRouteImport } from './routes/forum.$postId'

const WaRoute = WaRouteImport.update({
  id: '/wa',
  path: '/wa',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsRoute = SectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformsRoute = PlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSetupRoute = BusinessSetupRouteImport.update({
  id: '/business-setup',
  path: '/business-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumPostIdRoute = ForumPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => ForumRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/business-setup': typeof BusinessSetupRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/forum': typeof ForumRouteWithChildren
  '/platforms': typeof PlatformsRoute
  '/privacy': typeof PrivacyRoute
  '/sectors': typeof SectorsRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/wa': typeof WaRoute
  '/forum/$postId': typeof ForumPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/business-setup': typeof BusinessSetupRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/forum': typeof ForumRouteWithChildren
  '/platforms': typeof PlatformsRoute
  '/privacy': typeof PrivacyRoute
  '/sectors': typeof SectorsRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/wa': typeof WaRoute
  '/forum/$postId': typeof ForumPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/business-setup': typeof BusinessSetupRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/forum': typeof ForumRouteWithChildren
  '/platforms': typeof PlatformsRoute
  '/privacy': typeof PrivacyRoute
  '/sectors': typeof SectorsRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/wa': typeof WaRoute
  '/forum/$postId': typeof ForumPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/business-setup'
    | '/contact'
    | '/events'
    | '/forum'
    | '/platforms'
    | '/privacy'
    | '/sectors'
    | '/security'
    | '/terms'
    | '/wa'
    | '/forum/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/business-setup'
    | '/contact'
    | '/events'
    | '/forum'
    | '/platforms'
    | '/privacy'
    | '/sectors'
    | '/security'
    | '/terms'
    | '/wa'
    | '/forum/$postId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/business-setup'
    | '/contact'
    | '/events'
    | '/forum'
    | '/platforms'
    | '/privacy'
    | '/sectors'
    | '/security'
    | '/terms'
    | '/wa'
    | '/forum/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BusinessSetupRoute: typeof BusinessSetupRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  ForumRoute: typeof ForumRouteWithChildren
  PlatformsRoute: typeof PlatformsRoute
  PrivacyRoute: typeof PrivacyRoute
  SectorsRoute: typeof SectorsRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  WaRoute: typeof WaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wa': {
      id: '/wa'
      path: '/wa'
      fullPath: '/wa'
      preLoaderRoute: typeof WaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors': {
      id: '/sectors'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platforms': {
      id: '/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof PlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-setup': {
      id: '/business-setup'
      path: '/business-setup'
      fullPath: '/business-setup'
      preLoaderRoute: typeof BusinessSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$postId': {
      id: '/forum/$postId'
      path: '/$postId'
      fullPath: '/forum/$postId'
      preLoaderRoute: typeof ForumPostIdRouteImport
      parentRoute: typeof ForumRoute
    }
  }
}

interface ForumRouteChildren {
  ForumPostIdRoute: typeof ForumPostIdRoute
}

const ForumRouteChildren: ForumRouteChildren = {
  ForumPostIdRoute: ForumPostIdRoute,
}

const ForumRouteWithChildren = ForumRoute._addFileChildren(ForumRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BusinessSetupRoute: BusinessSetupRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  ForumRoute: ForumRouteWithChildren,
  PlatformsRoute: PlatformsRoute,
  PrivacyRoute: PrivacyRoute,
  SectorsRoute: SectorsRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  WaRoute: WaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
